"""
Constants live here
"""
import collections

valid_qs_and_as = {
    'ADOS1': collections.OrderedDict([
        ('ados1_a1', [0, 1, 2, 3, 8]),
        ('ados1_a2', [0, 1, 2, 3]),
        ('ados1_a3', [0, 1, 2, 8]),
        ('ados1_a4', [0, 1, 2, 3, 8]),
        ('ados1_a5', [0, 1, 2, 3, 8]),
        ('ados1_a6', [0, 1, 2, 8]),
        ('ados1_a7', [0, 1, 2, 3]),
        ('ados1_a8', [0, 1, 2, 8]),

        ('ados1_b1', [0, 2]),
        ('ados1_b2', [0, 1, 2, 3]),
        ('ados1_b3', [0, 1, 2]),
        ('ados1_b4', [0, 1, 2, 3]),
        ('ados1_b5', [0, 1, 2]),
        ('ados1_b6', [0, 1, 2, 3]),
        ('ados1_b7', [0, 1, 2, 3]),
        ('ados1_b8', [0, 1, 2]),
        ('ados1_b9', [0, 1, 2]),
        ('ados1_b10', [0, 1, 2]),
        ('ados1_b11', [0, 1, 2, 3]),
        ('ados1_b12', [0, 1, 2, 3]),

        ('ados1_c1', [0, 1, 2, 3]),
        ('ados1_c2', [0, 1, 2, 3]),

        ('ados1_d1', [0, 1, 2]),
        ('ados1_d2', [0, 1, 2]),
        ('ados1_d3', [0, 1, 2]),
        ('ados1_d4', [0, 1, 2, 3]),

        ('ados1_e1', [0, 1, 2, 7]),
        ('ados1_e2', [0, 1, 2]),
        ('ados1_e3', [0, 1, 2]),
    ]

    ),
    'ADOS2': collections.OrderedDict([
        ('ados2_a1', [0, 1, 2, 3, 7]),
        ('ados2_a2', [0, 1, 2, 7]),
        ('ados2_a3', [0, 1, 2, 7, 8]),
        ('ados2_a4', [0, 1, 2, 3]),
        ('ados2_a5', [0, 1, 2, 3]),
        ('ados2_a6', [0, 1, 2, 3]),
        ('ados2_a7', [0, 1, 2, 3]),
        ('ados2_a8', [0, 1, 2, 3, 8]),

        ('ados2_b1', [0, 2]),
        ('ados2_b2', [0, 1, 2]),
        ('ados2_b3', [0, 1, 2, 8]),
        ('ados2_b4', [0, 1, 2, 3]),
        ('ados2_b5', [0, 1, 2]),
        ('ados2_b6', [0, 1, 2]),
        ('ados2_b7', [0, 1, 2, 3]),
        ('ados2_b8', [0, 1, 2, 3]),
        ('ados2_b9', [0, 1, 2, 3]),
        ('ados2_b10', [0, 1, 2, 3]),
        ('ados2_b11', [0, 1, 2, 3]),

        ('ados2_c1', [0, 1, 2, 3]),
        ('ados2_c2', [0, 1, 2, 3]),

        ('ados2_d1', [0, 1, 2]),
        ('ados2_d2', [0, 1, 2]),
        ('ados2_d3', [0, 1, 2]),
        ('ados2_d4', [0, 1, 2, 3]),

        ('ados2_e1', [0, 1, 2, 7]),
        ('ados2_e2', [0, 1, 2]),
        ('ados2_e3', [0, 1, 2]),

    ]
    )
}
question_responses_only_in_new_version = [
            ('ados1_a1', 4),
            ('ados1_b5', 3),
            ('ados1_d1', 3),
            ('ados1_d2', 3),
            ('ados1_e1', 3),
            ('ados1_e2', 3),
            ('ados2_d1', 3),
            ('ados2_d2', 3),
            ('ados2_e3', 3),
        ]
ADOS_versions = ['v1', 'v2']

ADOS_v1_vs_v2_mapping_raw = [
    {'v1_key': 'ados1_a1', 'v2_key': 'ados1_a1', 'details_of_question_or_answer_changes': 'mapping of answer, plus minor clarifications, probably not a big deal',
        'v1_to_v2_answer_mapping': {'8': '4'}, 'v2_to_v1_answer_mapping': {'4': '8'}},
    {'v1_key': 'ados1_a2', 'v2_key': 'ados1_a2', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados1_a3', 'v2_key': 'ados1_a3', 'details_of_question_or_answer_changes': 'Medium clarifications'},
    {'v1_key': 'ados1_a4', 'v2_key': 'ados1_a4', 'details_of_question_or_answer_changes': 'Medium clarifications'},
    {'v1_key': 'ados1_a5', 'v2_key': 'ados1_a5', 'details_of_question_or_answer_changes': 'Medium clarifications'},
    {'v1_key': 'ados1_a6', 'v2_key': 'ados1_a6', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados1_a7', 'v2_key': 'ados1_a7', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados1_a8', 'v2_key': 'ados1_a8', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados1_b1', 'v2_key': 'ados1_b1', 'details_of_question_or_answer_changes': 'Trivial clarifications'},
    {'v1_key': 'ados1_b2', 'v2_key': 'ados1_b2', 'details_of_question_or_answer_changes': 'Trivial clarifications'},
    {'v1_key': 'ados1_b3', 'v2_key': 'ados1_b3', 'details_of_question_or_answer_changes': 'Answer 2 minor change in meaning'},
    {'v1_key': 'ados1_b4', 'v2_key': 'ados1_b4', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados1_b5', 'v2_key': 'ados1_b5', 'details_of_question_or_answer_changes': 'Splitting of answer plus minor clarifications',
        'v1_to_v2_answer_mapping': {'2': ['2','3']}, 'v2_to_v1_answer_mapping': {'3': '2'}},
    {'v1_key': 'ados1_b6', 'v2_key': 'ados1_b6', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados1_b7', 'v2_key': 'ados1_b7', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados1_b8', 'v2_key': 'ados1_b8', 'details_of_question_or_answer_changes': 'Minor change in meaning of response 1, minor clarifications'},
    {'v1_key': 'ados1_b9', 'v2_key': 'ados1_b9', 'details_of_question_or_answer_changes': ''},
    {'v1_key': 'ados1_b10', 'v2_key': 'ados1_b10', 'details_of_question_or_answer_changes': ''},
    {'v1_key': 'ados1_b11', 'v2_key': 'ados1_b11', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados1_b12', 'v2_key': 'ados1_b12', 'details_of_question_or_answer_changes': 'Trivial clarifications'},
    {'v1_key': None, 'v2_key': 'ados1_b13a'},
    {'v1_key': None, 'v2_key': 'ados1_b13b'},
    {'v1_key': None, 'v2_key': 'ados1_b14'},
    {'v1_key': None, 'v2_key': 'ados1_b15'},
    {'v1_key': None, 'v2_key': 'ados1_b16'},
    {'v1_key': 'ados1_c1', 'v2_key': 'ados1_c1', 'details_of_question_or_answer_changes': 'Trivial clarifications'},
    {'v1_key': 'ados1_c2', 'v2_key': 'ados1_c2', 'details_of_question_or_answer_changes': 'Trivial clarifications'},
    #### d1 <=> d4 same topics in v1 versus v2 except that in v2 weird reactions to sights/smells would go into d4, while in v1 it would
    ######## go into d1
    {'v1_key': 'ados1_d1', 'v2_key': 'ados1_d1', 'details_of_question_or_answer_changes': 'New answer code and significant clarifications',
        'v1_to_v2_answer_mapping': {'2': ['2','3']}, 'v2_to_v1_answer_mapping': {'3': '2'}},
    {'v1_key': 'ados1_d2', 'v2_key': 'ados1_d2', 'details_of_question_or_answer_changes': 'New answer code and significant clarifications',
        'v1_to_v2_answer_mapping': {'2': ['2','3']}, 'v2_to_v1_answer_mapping': {'3': '2'}},
    {'v1_key': 'ados1_d3', 'v2_key': 'ados1_d3', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados1_d4', 'v2_key': 'ados1_d4', 'details_of_question_or_answer_changes': 'Major clarification, taking material from what used to be d1'},
    {'v1_key': 'ados1_e1', 'v2_key': 'ados1_e1', 'details_of_question_or_answer_changes': 'Answer remapping and minor clarifications',
        'v1_to_v2_answer_mapping': {'1': ['1','2'], '2': '3'}, 'v2_to_v1_answer_mapping': {'2': '1', '3': '2'}},
    {'v1_key': 'ados1_e2', 'v2_key': 'ados1_e2', 'details_of_question_or_answer_changes': 'Answer remapping and minor clarifications',
        'v1_to_v2_answer_mapping': {'1': ['1','2'], '2': ['2','3']}, 'v2_to_v1_answer_mapping': {'2': ['1', '2'], '3': '2'} },
    {'v1_key': 'ados1_e3', 'v2_key': 'ados1_e3', 'details_of_question_or_answer_changes': 'Minor clarifications'},


    {'v1_key': 'ados2_a1', 'v2_key': 'ados2_a1', 'details_of_question_or_answer_changes': 'mapping of answer, plus minor clarifications, probably not a big deal',
        'v1_to_v2_answer_mapping': {'7': '3'}, 'v2_to_v1_answer_mapping': {'3': ['3', '7']}},
    {'v1_key': 'ados2_a2', 'v2_key': None},
    {'v1_key': 'ados2_a3', 'v2_key': 'ados2_a2', 'details_of_question_or_answer_changes': 'Trivial clarifications'},
    {'v1_key': 'ados2_a4', 'v2_key': 'ados2_a3', 'details_of_question_or_answer_changes': 'Medium clarifications'},
    {'v1_key': 'ados2_a5', 'v2_key': 'ados2_a4', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados2_a6', 'v2_key': 'ados2_a5', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados2_a7', 'v2_key': 'ados2_a6', 'details_of_question_or_answer_changes': 'Medium clarifications'},
    {'v1_key': 'ados2_a8', 'v2_key': 'ados2_a7', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados2_b1', 'v2_key': 'ados2_b1', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados2_b2', 'v2_key': 'ados2_b2', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados2_b3', 'v2_key': 'ados2_b3', 'details_of_question_or_answer_changes': 'Significant rephrasing of responses',
        'v1_to_v2_answer_mapping': {'2': ['2','3'], '8': None}, 'v2_to_v1_answer_mapping': {'3': '2'}},
    {'v1_key': 'ados2_b4', 'v2_key': 'ados2_b4', 'details_of_question_or_answer_changes': 'Significant clarifications, and minor tightening of criteria'},
    {'v1_key': 'ados2_b5', 'v2_key': 'ados2_b5', 'details_of_question_or_answer_changes': ''},
    {'v1_key': 'ados2_b6', 'v2_key': 'ados2_b6', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados2_b7', 'v2_key': 'ados2_b7', 'details_of_question_or_answer_changes': 'Medium rephrasing'},
    {'v1_key': 'ados2_b8', 'v2_key': 'ados2_b8', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': None, 'v2_key': 'ados2_b9a', },
    {'v1_key': None, 'v2_key': 'ados2_b9b', },
    {'v1_key': 'ados2_b9', 'v2_key': 'ados2_b10', 'details_of_question_or_answer_changes': ''},
    {'v1_key': 'ados2_b10', 'v2_key': 'ados2_b11', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados2_b11', 'v2_key': 'ados2_b12', 'details_of_question_or_answer_changes': ''},
    {'v1_key': 'ados2_c1', 'v2_key': 'ados2_c1', 'details_of_question_or_answer_changes': 'Minor clarifications'},
    {'v1_key': 'ados2_c2', 'v2_key': 'ados2_c2', 'details_of_question_or_answer_changes': ''},
    {'v1_key': 'ados2_d1', 'v2_key': 'ados2_d1', 'details_of_question_or_answer_changes': 'New answer code and significant clarifications',
        'v1_to_v2_answer_mapping': {'2': ['2','3']}, 'v2_to_v1_answer_mapping': {'3': '2'}},
    {'v1_key': 'ados2_d2', 'v2_key': 'ados2_d2', 'details_of_question_or_answer_changes': 'New answer code and significant clarifications',
        'v1_to_v2_answer_mapping': {'2': ['2','3']}, 'v2_to_v1_answer_mapping': {'3': '2'}},
    {'v1_key': 'ados2_d3', 'v2_key': 'ados2_d3', 'details_of_question_or_answer_changes': 'Medium clarifications'},
    {'v1_key': 'ados2_d4', 'v2_key': 'ados2_d4', 'details_of_question_or_answer_changes': 'Major clarification, taking material from what used to be d1'},
    {'v1_key': 'ados2_e1', 'v2_key': 'ados2_e1', 'details_of_question_or_answer_changes': 'Answer remapping and minor clarifications',
        'v1_to_v2_answer_mapping': {'1': ['1','2'], '2': '3'}, 'v2_to_v1_answer_mapping': {'2': '1', '3': '2'}},
    {'v1_key': 'ados2_e2', 'v2_key': 'ados2_e2', 'details_of_question_or_answer_changes': 'Answer remapping and minor clarifications',
        'v1_to_v2_answer_mapping': {'1': ['1','2'], '2': ['2','3']}, 'v2_to_v1_answer_mapping': {'2': ['1', '2'], '3': '2'} },
    {'v1_key': 'ados2_e3', 'v2_key': 'ados2_e3', 'details_of_question_or_answer_changes': 'Minor clarifications'},
]